// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9qObGrDCk9EVQzgVkP3nypSqcAjIBxsU',
    appId: '1:1096672055025:web:b83ac0276d4f470532a350',
    messagingSenderId: '1096672055025',
    projectId: 'sr-music-app',
    authDomain: 'sr-music-app.firebaseapp.com',
    storageBucket: 'sr-music-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGJ_vnmSHaQd5z8gHjNkMCfbLeNEskxyE',
    appId: '1:1096672055025:android:222a0caf6a5a163432a350',
    messagingSenderId: '1096672055025',
    projectId: 'sr-music-app',
    storageBucket: 'sr-music-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVRfTTBE5jkwr2AaDuq9LUNzy7o644FQI',
    appId: '1:1096672055025:ios:546de20a2de85ba332a350',
    messagingSenderId: '1096672055025',
    projectId: 'sr-music-app',
    storageBucket: 'sr-music-app.firebasestorage.app',
    iosBundleId: 'com.example.srMusicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVRfTTBE5jkwr2AaDuq9LUNzy7o644FQI',
    appId: '1:1096672055025:ios:546de20a2de85ba332a350',
    messagingSenderId: '1096672055025',
    projectId: 'sr-music-app',
    storageBucket: 'sr-music-app.firebasestorage.app',
    iosBundleId: 'com.example.srMusicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9qObGrDCk9EVQzgVkP3nypSqcAjIBxsU',
    appId: '1:1096672055025:web:92e67d5a67a952e132a350',
    messagingSenderId: '1096672055025',
    projectId: 'sr-music-app',
    authDomain: 'sr-music-app.firebaseapp.com',
    storageBucket: 'sr-music-app.firebasestorage.app',
  );
}
